# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: '3'


tasks:
  default:
    desc: 列出所有命令
    cmds:
      - task --list
    silent: true

  build:
    desc: 编译 dotlink 可执行文件到 bin 目录
    cmds:
      - mkdir -p bin
      - go build -o bin/dotlink ./cmd/dotlink
    silent: true

  test:
    desc: 运行单元测试
    cmds:
      - go test -race ./...

  lint:
    desc: 运行 golangci-lint
    cmds:
      - golangci-lint run ./...

  e2e:
    desc: 运行 E2E 端到端测试
    deps: [build]
    cmds:
      - ./e2e_test.sh
